### ISSUE TITLE
w10d05 hw

### ISSUE THREAD

**Issue by luminousbeam** [ga-dc/whatever_conf#11]
https://github.com/luminousbeam/Mars-One

**Comment by jshawl** [comment]
Interesting topic choice! :+1: What interests you in this mission?

**Comment by luminousbeam** [comment]
What interests me the most is the fact that we have never been to Mars before and I am interested to know what it would take in order to not just reach Mars, but also have the necessary supplies and instruments in order to survive for the rest of your life on a desolate planet.  The individuals who will be chosen to go to Mars are agreeing to never return back to Earth, they are aware and willing to take this on as it is ground breaking.

**Comment by jshawl** [comment]
That's crazy!!! - really looking forward to this presentation :)
