### ISSUE TITLE
My topic

### ISSUE THREAD

**Issue by nclevine** [ga-dc/whatever_conf#15]
https://github.com/nclevine/everything_conf/tree/master

**Comment by adambray** [comment]
Hey Noah,

This looks like a fascinating subject! Your learning objectives could be a bit more concrete and ability based, but that's not a huge deal. Here are some examples of how I might re-write them.

Define 'medium specificity' in the context of comp. gen. art.
Describe the differences  between computer generated art and other media. 
Give some examples of works that embody this specificity.
