### ISSUE TITLE
Link to my Everything Conference Repo

### ISSUE THREAD

**Issue by htylerbrooks** [ga-dc/whatever_conf#18]
My journey as a web developer and how I plan to make myself better and make the world a better place with my apps.

**Comment by adambray** [comment]
Hey Tyler,

This looks good. As you prepare tonight / tomorrow, please make sure you think about how you can give something to your peers to take away!

Link to your repo for posterity (in case the other instructors need it):
https://github.com/htylerbrooks/everythingConf

-Adam

**Comment by htylerbrooks** [comment]
Got it! Thanks Adam.

Sincerely,
Tyler
