### ISSUE TITLE
Intro to screen scraping

### ISSUE THREAD

**Issue by nhashmi** [ga-dc/whatever_conf#19]
https://github.com/nhashmi/everything-conf

**Comment by jrhorn424** [comment]
> 1. What does scraping mean?
> 2. Why would you want to scrape data?
> 3. What are some useful gems and libraries that I can use to scrape data?

Great topic, and important for a variety of apps where you can't use existing APIs or datasets. :+1:

Learning objectives aren't questions, but you're really close with these. They're focused and high-level. To improve, I recommend starting with an action verb that captures what the audience should **do** with the information. Each objective should fit the "At the end of this presentation, you should be able to..." format. For example:

> 1. Define "scraping"
> 2. Explain when one would choose scraping over other options
> 3. Recall libraries that can be used to make scraping easier
