### ISSUE TITLE
everything_conf

### ISSUE THREAD

**Issue by julia-rose** [ga-dc/whatever_conf#29]
Everybody bout to get SCHOOLED on language learning software options!!!!

https://github.com/julia-rose/everything_conf

**Comment by jrhorn424** [comment]
These are great learning objectives. Very interesting topic!

> - Learners will understand the current landscape of language-learning software, free and $$$ paid
> - Learners will be able to contrast the strengths and weaknesses of various learning methods
> - Learners will gain new strategies for self-driven language learning

You've got the basic format for learning objectives down. :+1:

I might phrase them a bit differently, starting with an action verb and describing what an audience member can do with your new information ("understand" and "gain" aren't "doable").

> - Describe the free and paid options currently available for language-learning software
> - Contrast the strengths and weaknesses of various learning methods
> - Choose among strategies for self-driven language learning
