### ISSUE TITLE
w10d05 HW-- Link to my repo for Everything Conf!

### ISSUE THREAD

**Issue by Karen-O** [ga-dc/whatever_conf#3]
https://github.com/Karen-O/WDI-Everything-Conf_PRESENTATION

**Comment by jrhorn424** [comment]
It looks like this is a presentation on "how to learn", but I'm not sure. These learning objectives are not very clear or actionable:

> (1) The Game Plan-- And why both objectively and for you personally, it's actually very doable / not so crazy.
> (2) THE RULES -- "Nothing good comes easily"
> (3) The Rewards -- Personal, professional, and so much more.

I'd like to provide more feedback once you've revised your LOs. Just ping me here and I'll be glad to re-evaluate.

Some tips:  I recommend starting with an action verb that captures what the audience should **do** with the information. Each objective should fit the "At the end of this presentation, you should be able to..." format.

**Comment by Karen-O** [comment]
I see what you're saying. I wrote it more like 3 main "talking points" than
LO's... Which I do intend to be essentially the same, but I'll need to
restructure starting them off with action verbs (like you suggested).

I was purposefully vague because i felt like that would help to really
drive my point home. Likely, assumptions will be that I must be
exaggerating, but I'm not-- and I can back it up. If I state it up front
though, that'll provide time for prejudgment / biased thinking to take
place, which is what I want to avoid.

I'll figure out how to rewrite the LO's though-- I can be more targeted /
specific. I'll just replace them in my ReadMe file and let you know when,
if that works.(tonight).

Thanks Jeff!
