### ISSUE TITLE
spatial data production

### ISSUE THREAD

**Issue by nbumbarger** [ga-dc/whatever_conf#30]
https://github.com/nbumbarger/everything_conf

I'll demystify working with spatial data in Ruby, using a dead-simple demonstration of how to turn information with coordinates into a simple KML map document for Google Earth, and a dead-simple demonstration of how to get coordinates for your information in the first place using Geocoding.

**Comment by jrhorn424** [comment]
With so much dead-simplicity, I wonder whether I'll survive. :wink:

> - The goal of my presentation will be to show how simple it is to generate spatial information using text processing.
> - I'll show the structure of a simple KML document, and use Ruby to batch-convert a set of text into a KML features.
> - I'll demonstrate a technique for getting spatial coordinates in the first place using a geocoding API.
> - Finally, I'll tie the two together, converting a list of addresses into features on a map with a few lines of code.
> - A tertiary goal is to demonstrate the simplicity of text-procesing, and to encourage people to understand the data structures they are working with before turning to a gem. Sometimes data is simpler than you think.

I'm glad to see so much detail so soon! This is an exciting topic. You **almost** have learning objectives in the description to this issue. Learning objectives are the high-level bits people are likely to walk away from your presentation remembering.

I recommend starting with an action verb that captures what the audience should **do** with the information. Each objective should fit the "At the end of this presentation, you should be able to..." format. For example:

> - Obtain spatial data using `geocoder`
> - Demonstrate using simple spatial data in Ruby
> - Generate KML documents for use with Google Earth

Keep these in mind when editing your presentation. Try to stay focused on giving just enough information to satisfy each point, and you should come in at or under twelve minutes.
