### ISSUE TITLE
Self Referential Associations

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/whatever_conf#35]
https://github.com/lmdragun/everything_conf

**Comment by jrhorn424** [comment]
> # everything conf presentations: Arduino
> 
> ## Learning Objectives:
> - Demonstrate Arduino Circuit board basics
> - Students should understand how javascript code can cause basic functions

I was excited to see something on self-referential associations! Arduinos are cool too, though. :smile:

These aren't clear or focused learning objectives.  I recommend starting with an action verb that captures what the audience should **do** with the information. Each objective should fit the "At the end of this presentation, you should be able to..." format. For example:

> - Recall the basic parts of a circuit board
> - Demonstrate where these parts are located on an Arduino board
> - Write a basic program to manipulate an Arduino
