### ISSUE TITLE
everything conf

### ISSUE THREAD

**Issue by KMG112** [ga-dc/whatever_conf#36]
https://github.com/KMG112/everythingconf

**Comment by jrhorn424** [comment]
> # everythingconf
> 1. Know what AWS is
> 2. understand the process by which amazon wants you to upload objects
> 3. what options are available

These aren't very clear or actionable. I recommend starting with an action verb that captures what the audience should **do** with the information. Each objective should fit the "At the end of this presentation, you should be able to..." format. For example:

> 1. Explain how AWS differs from other services, such as Heroku
> 2. Reference documentation or tutorials on how to use AWS S3 to store file uploads
> 3. Recall the services offered by AWS
