### ISSUE TITLE
Presentation 101 (bis)

### ISSUE THREAD

**Issue by mugshepherd** [ga-dc/whatever_conf#40]
https://github.com/mugshepherd/presentation_101/blob/master/README.md

Import Parity Price Analysis

What is import parity analysis and why would I use it?
How do I do import parity price analysis?
Where can I get data for import parity price analysis?

**Comment by jshawl** [comment]
:+1: Interesting idea! I know literally _nothing_ about parity price analysis - looking forward to learning more :)
