### ISSUE TITLE
Presentation 101:  the basics

### ISSUE THREAD

**Issue by mugshepherd** [ga-dc/whatever_conf#8]
https://github.com/mugshepherd/presentation_101

**Comment by jshawl** [comment]
Closing this as not turned in without learning objectives. Please reopen this issue when you have three learning objectives - happy to help if you need. Let me know!

**Comment by mugshepherd** [comment]
I was at a loss!  I’ve come up with an idea though and created a new issue.  
Thanks!  Toby
