### ISSUE TITLE
How to get started with Linux

### ISSUE THREAD

**Issue by keithknox** [ga-dc/whatever_conf#9]
https://github.com/keithknox/everything_conf_presentation

**Comment by jrhorn424** [comment]
Great topic. Really looking forward to it. :stars:

> 1. What is Linux?
> 2. Why would I want to use it?
> 3. How do I get started?

These LOs are okay. I recommend starting with an action verb that captures what the audience should **do** with the information. Each objective should fit the "At the end of this presentation, you should be able to..." format. For example:

> 1. Define "linux"
> 2. Explain why one would choose linux
> 3. Install linux and find software
